### PR TITLE
DM-6718 Add str and repr for afw catalog/record

### PR DESCRIPTION
**Pull request by parejkoj**
Re-merge, after fixing the variable-length arrays problem in DM-11429.

### CODE REVIEW

**Comment by timj** [comment]
there is no merge commit indicating that 2 of these commits were distinct.

**Comment by parejkoj** [comment]
I'm confused by your comment, @timj ? Why would there be such?

**Comment by timj** [comment]
Oh. I was confused by the base commit of this PR. Are you merging this branch directly to master or are you merging this branch to 11429 and then merging 11429 to master? I expected the latter.

**Comment by parejkoj** [comment]
I think my plan is to merge 11429 to master, then rebase this onto master (which shouldn't change anything), then merge this. But I'm open to suggestions.

**Comment by timj** [comment]
That is one option. Doing it in two stages like that is fine with me (so this PR is not itself being merged).

**Pull request merged**
